spring:
  datasource:
    url: ${DB_URL:jdbc:h2:mem:beneficiario}
    username: ${DB_USER:sa}
    password: ${DB_PASS:}
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
  jackson:
    deserialization:
      fail-on-unknown-properties: true
    date-format: yyyy-MM-dd
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
server:
  error:
    include-binding-errors: never
    include-message: never

