spring:
  datasource:
    url: ${DB_URL:jdbc:h2:mem:beneficiario}
    username: ${DB_USER:sa}
    password: ${DB_PASS:}
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop